### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by mandric** [ermakovich/pptr-mock-server#80]
Looks like a nice API to mock response data with but there are no bundled `.d.ts` files.  I see the type declarations in the source files but VS Code does not appear to find those in the distribution?  Any tips?

**Comment by ermakovich** [comment]
project code is not statically typed currently, so there is no type annotation files generated. These type declaration in the source files are JSDoc annotations required for generating documentation only.

**Comment by BitFis** [comment]
I took the liberty and created a gist for (my version) of the typings, feel free to use it. https://gist.github.com/BitFis/b51d413436a9cddec713ddb3108fb5b7
I will also happily update them, if you find issues and if @ermakovich whats to add them to the repository remove them.

Hope those help, love the module ❤️ 

Cheers

**Comment by ermakovich** [comment]
@BitFis sorry for delayed response. Gist looks great. My only concern is that it will be needed to maintain annotations in two places, since JSDoc annotations are still required for docs generation. I'm not sure, maybe it's possible to auto-generate docs from TS annotations, something similar to https://github.com/ermakovich/pptr-mock-server/blob/master/api.md?

In any case, I will be happy to include this into the repo and accepting efforts to maintain annotations in two places for now. Would you mind to create PR please?

**Comment by BitFis** [comment]
@ermakovich I agree, double maintenance is not great, what about moving the jsdoc documentation to typescript, as it is more expressive? I know you might not like this approach, but as you know, typescript contains more information and there for is easier to convert to js then other way around. So that might be the more natural way? 🤔
